[package]
name = "eqsolver"
version = "0.1.2"
edition = "2021"
description = "A library that solves equations using numerical methods"
repository = "https://github.com/AzeezDa/eqsolver"
license = "MIT"
readme = "README.md"
keywords = ["equation", "solver", "mathematics", "ode"]
categories = ["science", "mathematics", "algorithms"]

[badges]
maintenance = { status = "passively-maintained" }

[lib]
name = "eqsolver"
path = "src/lib.rs"

[dependencies]
nalgebra = "0.32.2"
num-traits = "0.2.15"