[package]
name = "eqsolver"
version = "0.1.1"
edition = "2021"
description = "A library that solves equations using numerical methods"
repository = "https://github.com/AzeezDa/eqsolver"
license = "MIT"
readme = "README.md"
keywords = ["equation", "solver", "math"]
categories = ["science", "mathematics"]

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "eqsolver"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.0"
num-traits = "0.2.15"